name: Run IL-CLI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run-imaging-cloud-cli:
    runs-on: castimaging/carl-java-cli:alpha
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check DIR
        run: ls -al
