name: Create issue on commit

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Post GH Token
        run: |
          curl --request GET \
          --url https://api.github.com/user
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --fail
